name: Build for Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        # Agregar otras dependencias aquí
        # pip install -r requirements.txt
    
    - name: Build with PyInstaller
      run: |
        pyinstaller \
          --onefile \
          --windowed \
          --name="GestionInventario" \
          --add-data="config:config" \
          --add-data="models:models" \
          --add-data="utils:utils" \
          --add-data="database:database" \
          main.py
    
    - name: Create distribution package
      run: |
        mkdir -p GestionInventario-Linux/
        cp dist/GestionInventario GestionInventario-Linux/
        cp -r database/ GestionInventario-Linux/ 2>/dev/null || true
        
        # Crear script de ejecución
        cat > GestionInventario-Linux/ejecutar.sh << 'EOF'
        #!/bin/bash
        cd "$(dirname "$0")"
        ./GestionInventario
        EOF
        chmod +x GestionInventario-Linux/ejecutar.sh
        
        # Comprimir
        tar -czf GestionInventario-Linux.tar.gz GestionInventario-Linux/
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: GestionInventario-Linux
        path: |
          GestionInventario-Linux.tar.gz
          GestionInventario-Linux/